name = input("Enter name: ")
marks = int(input("enter marks: "))
phone = int(input("Enter number: "))
s = "The name of the student is {}, his marks are {} and phone number is {}".format(name, marks, phone)
print(s)
