# a=(1,'j',99,False,"rohan",99)
# print(type(a))
# print(a)
# no=a.count(99)
# print(no)

fruits=[]
f1 = input("Enter Fruit name:")
fruits.append(f1)
f2 = input("Enter Fruit name:")
fruits.append(f2)
f3 = input("Enter Fruit name:")
fruits.append(f3)
f4 = input("Enter Fruit name:")
fruits.append(f4)
print(fruits)
